[workspace]
resolver = "2"
members = [
    "node",
    "pallets/pallet-cgt",
    "pallets/pallet-qor-identity",
    "pallets/pallet-drc369",
    "runtime",
]

[workspace.package]
version = "0.1.0"
authors = ["Alaustrup <alaustrup@demiurge.io>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Alaustrup/Demiurge-Blockchain"

[workspace.dependencies]
# Substrate dependencies (use latest polkadot-stable branch)
frame-support = { version = "38.0.0", default-features = false }
frame-system = { version = "38.0.0", default-features = false }
frame-benchmarking = { version = "38.0.0", default-features = false }
sp-core = { version = "35.0.0", default-features = false }
sp-io = { version = "38.0.0", default-features = false }
sp-runtime = { version = "39.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
pallet-balances = { version = "39.0.0", default-features = false }
pallet-timestamp = { version = "37.0.0", default-features = false }

# Encoding
codec = { package = "parity-scale-codec", version = "3.7", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }

# Local pallets
pallet-cgt = { path = "pallets/pallet-cgt", default-features = false }
pallet-qor-identity = { path = "pallets/pallet-qor-identity", default-features = false }
pallet-drc369 = { path = "pallets/pallet-drc369", default-features = false }